name: flutter_resonance_audio_example
description: Demonstrates how to use the flutter_resonance_audio plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_resonance_audio:
    path: ../

flutter:
  uses-material-design: true

  assets:
   - sound/c.ogg
   - sound/d.ogg
   - sound/e.ogg
   - sound/f.ogg
   - sound/g.ogg
   - sound/a.ogg
   - sound/b.ogg
